#!/bin/bash

echo -e "<div><style>span{color:orange;}</style><span>I hope you had a good time with CustomStatusBar 😊</span>"
echo -e "<div><style>span{color:orange;}</style><span>If you uninstalled CustomStatusBar because you had issues please report them to me!</span>"
